### PR TITLE
Detail page

### PR DESCRIPTION
**Pull request by XOQDY**
After doing this page for a long time I finished it my friend so allow me to merge pls my friend.

### CODE REVIEW

**Review by Jakarin-Jojo — CHANGES_REQUESTED** [review]
This is looking good but has no test case.

**Review by bhokin — COMMENTED** [review]
Yeah, you should have a test view.

**Comment by XOQDY** [comment]
I have added test as per order. SIR YES SIR!!!!!!!!!

**Comment by Jakarin-Jojo** [comment]
Good!

**Review by Jakarin-Jojo — APPROVED** [review]

**Pull request merged**
