### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by NamoSmith**
- Improve Sign in and Sign up code quality.
- Link sign in and sign up page with main.

### CODE REVIEW

**Comment by Jakarin-Jojo** [comment]
This branch has no conflicts When merging. but you should add some tests.

**Comment by NamoSmith** [comment]
My branch now have tests

**Comment by bhokin** [comment]
Travis builds passed! Look good

**Comment by Jakarin-Jojo** [comment]
That Good.

**Pull request merged**
